import { useEffect, useState } from 'react';
import { Navigate } from 'react-router-dom';
import api from './services/api';
import { useAuth } from './context/AuthContext';

const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);
const emptyProduct = { name: '', slug: '', category: '', price: '', mrp: '', stock: '', images: [], imageUrl: '', shortDescription: '', description: '', power: '', size: '', color: '', material: '', brand: 'ETN Melody', shape: '', countryOfOrigin: 'India', packagingType: '', modelNameNumber: '', extraSpecifications: [], featured: false };
const slugify = value => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const standardSpecificationKeys = new Set(['Power','Size','Color','Material','Brand','Shape','Country of Origin','Packaging Type','Model Name/Number']);

export default function Admin() {
  const { user, loading } = useAuth();
  const [data, setData] = useState(null), [categories, setCategories] = useState([]), [products, setProducts] = useState([]), [inquiries, setInquiries] = useState([]), [orders, setOrders] = useState([]), [users, setUsers] = useState([]);
  const [section, setSection] = useState('dashboard'), [editingId, setEditingId] = useState(null);
  const [form, setForm] = useState(emptyProduct), [newCategory, setNewCategory] = useState(''), [error, setError] = useState(''), [message, setMessage] = useState(''), [saving, setSaving] = useState(false), [uploading, setUploading] = useState(false), [uploadProgress, setUploadProgress] = useState(0);
  const loadAdmin = async () => {
    const optional=(request,fallback)=>request.catch(()=>({data:fallback}));
    const [dashboard, categoryList, productList, inquiryList, orderList, userList] = await Promise.all([api.get('/admin/dashboard'),optional(api.get('/admin/categories'),{categories:[]}),optional(api.get('/admin/products'),{products:[]}),optional(api.get('/admin/inquiries'),{inquiries:[]}),optional(api.get('/admin/orders'),{orders:[]}),optional(api.get('/admin/users'),{users:[]})]);
    setData(dashboard.data); setCategories(categoryList.data.categories); setProducts(productList.data.products); setInquiries(inquiryList.data.inquiries); setOrders(orderList.data.orders); setUsers(userList.data.users);
  };
  useEffect(() => { if (user?.role === 'admin') loadAdmin().catch(e => setError(e.response?.data?.message || 'Unable to load admin panel.')); }, [user?.role]);
  const update = e => { const { name, value, type, checked } = e.target; setForm(current => ({ ...current, [name]: type === 'checkbox' ? checked : value })); };
  const submit = async e => {
    e.preventDefault(); setSaving(true); setError(''); setMessage('');
    try {
      const customSpecifications=Object.fromEntries(form.extraSpecifications.filter(item=>item.key.trim()&&item.value.trim()).map(item=>[item.key.trim(),item.value.trim()]));
      const productData={ name: form.name.trim(), slug: form.slug.trim() || slugify(form.name), category: form.category, brand: form.brand.trim() || 'ETN Melody', price: Number(form.price), mrp: form.mrp ? Number(form.mrp) : undefined, stock: Number(form.stock || 0), images: [...form.images, ...(form.imageUrl.trim() ? [form.imageUrl.trim()] : [])], shortDescription: form.shortDescription.trim(), description: form.description.trim(), specifications: { ...customSpecifications,Power:form.power.trim(),Size:form.size.trim(),Color:form.color.trim(),Material:form.material.trim(),Brand:form.brand.trim(),Shape:form.shape.trim(),'Country of Origin':form.countryOfOrigin.trim(),'Packaging Type':form.packagingType.trim(),'Model Name/Number':form.modelNameNumber.trim() }, featured: form.featured };
      editingId?await api.put(`/admin/products/${editingId}`,productData):await api.post('/admin/products',productData);
      setForm(emptyProduct);setEditingId(null);setMessage(editingId?'Product updated successfully.':'Product added successfully.');await loadAdmin();
    } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to add product. Check every required field.'); }
    finally { setSaving(false); }
  };
  const editProduct = product => {
    const specs=product.specifications||{};
    setForm({name:product.name||'',slug:product.slug||'',category:product.category?._id||product.category||'',price:product.price??'',mrp:product.mrp??'',stock:product.stock??'',images:product.images||[],imageUrl:'',shortDescription:product.shortDescription||'',description:product.description||'',power:specs.Power||'',size:specs.Size||'',color:specs.Color||'',material:specs.Material||'',brand:product.brand||specs.Brand||'ETN Melody',shape:specs.Shape||'',countryOfOrigin:specs['Country of Origin']||'India',packagingType:specs['Packaging Type']||'',modelNameNumber:specs['Model Name/Number']||'',extraSpecifications:Object.entries(specs).filter(([key])=>!standardSpecificationKeys.has(key)).map(([key,value])=>({key,value})),featured:!!product.featured});
    setEditingId(product._id);setError('');setMessage('');document.getElementById('product-form')?.scrollIntoView({behavior:'smooth',block:'start'});
  };
  const cancelEdit=()=>{setEditingId(null);setForm(emptyProduct);setError('');setMessage('')};
  const addSpecification=()=>setForm(current=>({...current,extraSpecifications:[...current.extraSpecifications,{key:'',value:''}]}));
  const updateSpecification=(index,field,value)=>setForm(current=>({...current,extraSpecifications:current.extraSpecifications.map((item,i)=>i===index?{...item,[field]:value}:item)}));
  const removeSpecification=index=>setForm(current=>({...current,extraSpecifications:current.extraSpecifications.filter((_,i)=>i!==index)}));
  const deleteProduct=async product=>{if(!window.confirm(`Delete "${product.name}" from the store?`))return;setError('');setMessage('');try{await api.delete(`/admin/products/${product._id}`);setProducts(current=>current.filter(item=>item._id!==product._id));if(editingId===product._id)cancelEdit();const dashboard=await api.get('/admin/dashboard');setData(dashboard.data);setMessage('Product deleted successfully.')}catch(requestError){setError(requestError.response?.data?.message||'Unable to delete product.')}};
  const createCategory = async () => {
    if (!newCategory.trim()) return;
    setSaving(true); setError('');
    try {
      const result = await api.post('/admin/categories', { name: newCategory });
      setCategories(current => [...current, result.data.category].sort((a, b) => a.name.localeCompare(b.name)));
      setForm(current => ({ ...current, category: result.data.category._id }));
      setNewCategory(''); setMessage('Category created. You can now add the product.');
    } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to create category.'); }
    finally { setSaving(false); }
  };
  const uploadImages = async event => {
    const files = Array.from(event.target.files || []);
    if (!files.length) return;
    if (form.images.length + files.length > 8) { setError('You can upload a maximum of 8 product images.'); event.target.value=''; return; }
    if (files.some(file => !file.type.startsWith('image/'))) { setError('Please select only valid image files.'); event.target.value=''; return; }
    if (files.some(file => file.size > 5 * 1024 * 1024)) { setError('Each image must be 5 MB or smaller.'); event.target.value=''; return; }
    setUploading(true); setUploadProgress(0); setError(''); setMessage('');
    try {
      const body = new FormData(); files.forEach(file => body.append('images', file));
      const result = await api.post('/admin/upload', body, { headers: { 'Content-Type': 'multipart/form-data' }, onUploadProgress: progress => setUploadProgress(progress.total ? Math.round(progress.loaded * 100 / progress.total) : 0) });
      setForm(current => ({ ...current, images: [...current.images, ...result.data.images.map(image => image.url)] }));
      setMessage(`${result.data.images.length} product image${result.data.images.length===1?'':'s'} uploaded successfully.`);
    } catch (requestError) { setError(requestError.response?.data?.message || 'Image upload failed. Check the Cloudinary configuration.'); }
    finally { setUploading(false); event.target.value = ''; }
  };
  const updateUser = async (id, changes) => {
    setError(''); setMessage('');
    try {
      const result = await api.patch(`/admin/users/${id}`, changes);
      setUsers(current => current.map(item => item._id === id ? result.data.user : item));
      setMessage('User account updated successfully.');
    } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to update user.'); }
  };
  const updateOrder = async (id, changes) => {
    setError(''); setMessage('');
    try {
      const result = await api.patch(`/admin/orders/${id}`, changes);
      setOrders(current => current.map(order => order._id === id ? { ...order, ...result.data.order } : order));
      setMessage('Order status updated successfully.');
      const dashboard = await api.get('/admin/dashboard'); setData(dashboard.data);
    } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to update order.'); }
  };
  const updateInquiry = async (id,status) => {
    setError('');setMessage('');
    try{const result=await api.patch(`/admin/inquiries/${id}`,{status});setInquiries(current=>current.map(item=>item._id===id?result.data.inquiry:item));setMessage('Enquiry status updated.');const dashboard=await api.get('/admin/dashboard');setData(dashboard.data)}
    catch(requestError){setError(requestError.response?.data?.message||'Unable to update enquiry.')}
  };
  if (loading) return <main className="wrap py-20">Loading admin panel…</main>;
  if (user?.role !== 'admin') return <Navigate to="/login" replace />;
  if (!data && !error) return <main className="wrap py-20">Loading admin dashboard…</main>;
  const stats = data ? [['New enquiries', data.inquiries||0], ['Products', data.products||0], ['Orders', data.orders||0], ['Total sales', money(data.totalSales)]] : [];
  return <main className="wrap py-10">
    <p className="text-sm font-bold text-signal">ADMINISTRATION</p><h1 className="text-4xl font-bold">Store control centre</h1>
    <nav className="mt-7 flex gap-2 overflow-x-auto rounded-2xl bg-ink p-2">{[['dashboard','Dashboard'],['products','Products'],['inquiries','Enquiries'],['orders','Orders'],['users','Users']].map(([key,label]) => <button key={key} onClick={() => { setSection(key); setError(''); setMessage(''); }} className={`whitespace-nowrap rounded-xl px-5 py-3 text-sm font-bold transition ${section===key?'bg-signal text-white':'text-slate-300 hover:bg-slate-800 hover:text-white'}`}>{label}{key==='inquiries'&&data?.inquiries>0?<span className="ml-2 rounded-full bg-white px-2 py-0.5 text-[10px] text-signal">{data.inquiries}</span>:null}</button>)}</nav>
    {error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{message && <p className="mt-5 rounded-xl bg-green-50 p-4 text-green-700">{message}</p>}
    {section === 'dashboard' && <><section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([label, value]) => <div className="card p-5" key={label}><p className="text-sm font-bold text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>)}</section>
      <section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="card p-6"><h2 className="text-xl font-bold">Recent orders</h2><div className="mt-4 space-y-3">{data?.recentOrders?.map(order => <div key={order._id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><p className="font-bold">{order.orderNumber || order._id.slice(-8)}</p><p className="text-xs text-slate-500">{order.orderStatus}</p></div><b>{money(order.total)}</b></div>)}{!data?.recentOrders?.length && <p className="text-sm text-slate-500">No orders yet.</p>}</div></div><div className="card p-6"><h2 className="text-xl font-bold">Low stock</h2><div className="mt-4 space-y-3">{data?.lowStock?.map(product => <div key={product._id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><span className="font-bold">{product.name}</span><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">{product.stock} left</span></div>)}{!data?.lowStock?.length && <p className="text-sm text-slate-500">Stock levels look healthy.</p>}</div></div></section></>}
    {section === 'products' && <><section id="product-form" className="card mt-8 scroll-mt-28 p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-bold">{editingId?'Edit product':'Add product'}</h2><p className="mt-1 text-sm text-slate-500">{editingId?'Update the product details and save your changes.':'Fields marked * are required.'}</p></div>{editingId&&<button type="button" onClick={cancelEdit} className="rounded-full border px-4 py-2 text-sm font-bold hover:bg-slate-50">Cancel</button>}</div>
      {!categories.length && <p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">No categories exist yet. Create the first category below.</p>}
      <form onSubmit={submit} className="mt-6 grid gap-4 md:grid-cols-2">
        <Field label="Product name *"><input required name="name" value={form.name} onChange={update} className="field" placeholder="ETN Melody Piezo Tweeter" /></Field>
        <Field label="Slug"><input name="slug" value={form.slug} onChange={update} className="field" placeholder="Generated automatically" /></Field>
        <Field label="Category *"><select required name="category" value={form.category} onChange={update} className="field"><option value="">Select category</option>{categories.map(c => <option key={c._id} value={c._id}>{c.name}</option>)}</select><div className="mt-2 flex gap-2"><input value={newCategory} onChange={e => setNewCategory(e.target.value)} className="field" placeholder="New category name" /><button type="button" disabled={saving || !newCategory.trim()} onClick={createCategory} className="btn-dark shrink-0 disabled:opacity-50">Create</button></div></Field>
        <Field label="Selling price (₹) *"><input required min="0" step="0.01" type="number" name="price" value={form.price} onChange={update} className="field" /></Field>
        <Field label="MRP (₹)"><input min="0" step="0.01" type="number" name="mrp" value={form.mrp} onChange={update} className="field" /></Field>
        <Field label="Stock quantity *"><input required min="0" step="1" type="number" name="stock" value={form.stock} onChange={update} className="field" /></Field>
        <Field label="Product images"><div className="rounded-xl border-2 border-dashed border-slate-200 p-4"><input id="product-images" type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif" onChange={uploadImages} disabled={uploading||form.images.length>=8} className="block w-full text-sm file:mr-3 file:rounded-full file:border-0 file:bg-ink file:px-4 file:py-2 file:font-bold file:text-white hover:file:bg-slate-700 disabled:opacity-50" /><p className="mt-2 text-xs text-slate-500">Select up to 8 images at once. Maximum 5 MB per image. The first image is used as the cover.</p>{uploading && <div className="mt-3"><div className="h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-signal transition-all" style={{width:`${uploadProgress}%`}} /></div><p className="mt-1 text-xs text-slate-500">Uploading to Cloudinary… {uploadProgress}%</p></div>}{form.images.length>0 && <div className="mt-4 grid grid-cols-3 gap-3 sm:grid-cols-4">{form.images.map((image,index)=><div key={image} className="relative"><img src={image} alt={`Product preview ${index+1}`} className="h-24 w-full rounded-xl border object-cover" />{index===0&&<span className="absolute left-1 top-1 rounded bg-ink/80 px-2 py-1 text-[10px] font-bold text-white">Cover</span>}<button type="button" aria-label={`Remove image ${index+1}`} onClick={()=>setForm(current=>({...current,images:current.images.filter((_,i)=>i!==index)}))} className="absolute right-1 top-1 grid h-6 w-6 place-items-center rounded-full bg-red-600 text-xs font-bold text-white">×</button></div>)}</div>}</div><input type="url" name="imageUrl" value={form.imageUrl} onChange={update} className="field mt-2 text-xs" placeholder="Or paste one additional image URL" /></Field>
        <Field label="Short description" wide><input name="shortDescription" value={form.shortDescription} onChange={update} className="field" /></Field>
        <Field label="Full description" wide><textarea rows="4" name="description" value={form.description} onChange={update} className="field resize-y" /></Field>
        <div className="md:col-span-2 mt-2 border-t pt-5"><h3 className="text-xl font-bold">Product specifications</h3><p className="mt-1 text-sm text-slate-500">Technical information displayed on the product page.</p></div>
        <Field label="Power"><input name="power" value={form.power} onChange={update} className="field" placeholder="Example: 50 W" /></Field>
        <Field label="Size"><input name="size" value={form.size} onChange={update} className="field" placeholder="Example: 4 inch" /></Field>
        <Field label="Color"><input name="color" value={form.color} onChange={update} className="field" placeholder="Example: Black" /></Field>
        <Field label="Material"><input name="material" value={form.material} onChange={update} className="field" placeholder="Example: ABS Plastic" /></Field>
        <Field label="Brand"><input name="brand" value={form.brand} onChange={update} className="field" /></Field>
        <Field label="Shape"><input name="shape" value={form.shape} onChange={update} className="field" placeholder="Example: Round" /></Field>
        <Field label="Country of Origin"><input name="countryOfOrigin" value={form.countryOfOrigin} onChange={update} className="field" /></Field>
        <Field label="Packaging Type"><input name="packagingType" value={form.packagingType} onChange={update} className="field" placeholder="Example: Box" /></Field>
        <Field label="Model Name/Number"><input name="modelNameNumber" value={form.modelNameNumber} onChange={update} className="field" placeholder="Example: ETN-PT100" /></Field>
        <div className="md:col-span-2 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between gap-4"><div><h4 className="font-bold">Additional specifications</h4><p className="mt-1 text-xs text-slate-500">Add any extra product detail using your own field name.</p></div><button type="button" onClick={addSpecification} className="rounded-full bg-ink px-4 py-2 text-sm font-bold text-white hover:bg-signal">+ Add more field</button></div>{form.extraSpecifications.length>0&&<div className="mt-4 space-y-3">{form.extraSpecifications.map((item,index)=><div key={index} className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input value={item.key} onChange={e=>updateSpecification(index,'key',e.target.value)} className="field" placeholder="Field name, e.g. Frequency Range"/><input value={item.value} onChange={e=>updateSpecification(index,'value',e.target.value)} className="field" placeholder="Value, e.g. 50 Hz – 20 kHz"/><button type="button" onClick={()=>removeSpecification(index)} className="rounded-xl border border-red-200 px-4 py-2 text-sm font-bold text-red-600 hover:bg-red-50">Remove</button></div>)}</div>}</div>
        <label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" name="featured" checked={form.featured} onChange={update} className="h-4 w-4" /> Featured product</label>
        <div className="md:text-right"><button disabled={saving || uploading || !categories.length} className="btn-primary disabled:opacity-50">{saving ? (editingId?'Saving changes…':'Adding product…') : uploading ? 'Uploading image…' : editingId?'Save changes':'Add product'}</button></div>
      </form>
    </section>
    <section className="mt-8"><h2 className="text-2xl font-bold">Product catalogue</h2><div className="mt-4 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Product</th><th className="p-4">SKU</th><th className="p-4">Category</th><th className="p-4">Price</th><th className="p-4">Stock</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y">{products.map(p => <tr key={p._id}><td className="p-4"><div className="flex items-center gap-3">{p.images?.[0]&&<img src={p.images[0]} alt="" className="h-12 w-12 rounded-lg object-cover"/>}<span className="font-bold">{p.name}</span></div></td><td className="p-4">{p.sku}</td><td className="p-4">{p.category?.name || '—'}</td><td className="p-4">{money(p.price)}</td><td className="p-4">{p.stock}</td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={()=>editProduct(p)} className="rounded-full bg-ink px-4 py-2 text-xs font-bold text-white hover:bg-slate-700">Edit</button><button onClick={()=>deleteProduct(p)} className="rounded-full border border-red-200 px-4 py-2 text-xs font-bold text-red-600 hover:bg-red-50">Delete</button></div></td></tr>)}{!products.length && <tr><td colSpan="6" className="p-8 text-center text-slate-500">No products added yet.</td></tr>}</tbody></table></div></section></>}
    {section === 'inquiries' && <section className="mt-8"><div className="flex items-end justify-between"><div><h2 className="text-2xl font-bold">Product enquiries</h2><p className="mt-1 text-sm text-slate-500">Customer callback and quotation requests submitted from product pages.</p></div><span className="rounded-full bg-slate-200 px-3 py-1 text-sm font-bold">{inquiries.length} total</span></div><div className="mt-4 grid gap-4">{inquiries.map(inquiry=><article key={inquiry._id} className="card p-5"><div className="grid gap-5 lg:grid-cols-[1fr_1fr_auto]"><div className="flex gap-4">{inquiry.product?.images?.[0]&&<img src={inquiry.product.images[0]} alt="" className="h-20 w-20 rounded-xl object-cover"/>}<div><p className="text-xs font-bold uppercase tracking-wider text-signal">{inquiry.status}</p><h3 className="mt-1 font-bold">{inquiry.product?.name||'Deleted product'}</h3><p className="mt-1 text-xs text-slate-500">{new Date(inquiry.createdAt).toLocaleString('en-IN')}</p><p className="mt-2 text-sm"><b>Quantity:</b> {inquiry.quantity}{inquiry.material&&<> · <b>Material:</b> {inquiry.material}</>}</p></div></div><div className="text-sm"><p className="font-bold">{inquiry.name}{inquiry.company?` · ${inquiry.company}`:''}</p><a href={`tel:${inquiry.mobile}`} className="mt-2 block font-bold text-signal">{inquiry.mobile}</a><a href={`mailto:${inquiry.email}`} className="mt-1 block text-slate-600">{inquiry.email}</a>{inquiry.website&&<a href={inquiry.website} target="_blank" rel="noreferrer" className="mt-1 block text-blue-600">{inquiry.website}</a>}{inquiry.requirement&&<p className="mt-3 rounded-xl bg-slate-50 p-3 text-slate-600">{inquiry.requirement}</p>}</div><div><label className="label">Status</label><select value={inquiry.status} onChange={e=>updateInquiry(inquiry._id,e.target.value)} className="field min-w-36"><option>New</option><option>Contacted</option><option>Quoted</option><option>Closed</option></select></div></div></article>)}{!inquiries.length&&<div className="card p-10 text-center text-slate-500">No product enquiries yet.</div>}</div></section>}
    {section === 'orders' && <section className="mt-8"><div className="flex items-end justify-between"><div><h2 className="text-2xl font-bold">Order management</h2><p className="mt-1 text-sm text-slate-500">Review orders and update fulfilment progress.</p></div><span className="rounded-full bg-slate-200 px-3 py-1 text-sm font-bold">{orders.length} orders</span></div><div className="mt-4 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Order</th><th className="p-4">Customer</th><th className="p-4">Items</th><th className="p-4">Payment</th><th className="p-4">Total</th><th className="p-4">Status</th></tr></thead><tbody className="divide-y">{orders.map(order => <tr key={order._id}><td className="p-4"><p className="font-bold">{order.orderNumber || order._id.slice(-8)}</p><p className="text-xs text-slate-500">{new Date(order.createdAt).toLocaleString('en-IN')}</p></td><td className="p-4"><p className="font-bold">{order.user?.name || order.shippingAddress?.fullName || 'Guest'}</p><p className="text-xs text-slate-500">{order.user?.email || order.shippingAddress?.email || '—'}</p><p className="text-xs text-slate-500">{order.user?.phone || order.shippingAddress?.phone || '—'}</p></td><td className="p-4">{order.items?.reduce((sum,item)=>sum+item.quantity,0) || 0}</td><td className="p-4"><p className="mb-1 font-bold">{order.paymentMethod}</p><select aria-label={`Payment for order ${order.orderNumber || order._id}`} value={order.paymentStatus} onChange={e => updateOrder(order._id,{paymentStatus:e.target.value})} className="rounded-lg border px-2 py-1 text-xs"><option>Pending</option><option>Paid</option><option>Failed</option><option>Refunded</option></select></td><td className="p-4 font-bold">{money(order.total)}</td><td className="p-4"><select aria-label={`Status for order ${order.orderNumber || order._id}`} value={order.orderStatus} onChange={e => updateOrder(order._id,{orderStatus:e.target.value})} className="min-w-40 rounded-lg border px-3 py-2"><option>Pending</option><option>Confirmed</option><option>Processing</option><option>Shipped</option><option>Out for Delivery</option><option>Delivered</option><option>Cancelled</option></select></td></tr>)}{!orders.length && <tr><td colSpan="6" className="p-10 text-center text-slate-500">No orders have been placed yet.</td></tr>}</tbody></table></div></section>}
    {section === 'users' && <section className="mt-8"><h2 className="text-2xl font-bold">User management</h2><p className="mt-1 text-sm text-slate-500">Manage access and administrator permissions.</p><div className="mt-4 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">User</th><th className="p-4">Phone</th><th className="p-4">Joined</th><th className="p-4">Role</th><th className="p-4">Status</th></tr></thead><tbody className="divide-y">{users.map(account => { const self = String(account._id) === String(user.id || user._id); return <tr key={account._id}><td className="p-4"><p className="font-bold">{account.name}{self ? ' (You)' : ''}</p><p className="text-xs text-slate-500">{account.email}</p></td><td className="p-4">{account.phone || '—'}</td><td className="p-4">{new Date(account.createdAt).toLocaleDateString('en-IN')}</td><td className="p-4"><select aria-label={`Role for ${account.name}`} disabled={self} value={account.role} onChange={e => updateUser(account._id,{role:e.target.value})} className="rounded-lg border px-3 py-2 disabled:bg-slate-100"><option value="customer">Customer</option><option value="admin">Admin</option></select></td><td className="p-4"><button disabled={self} onClick={() => updateUser(account._id,{active:account.active===false})} className={`rounded-full px-3 py-2 text-xs font-bold text-white disabled:bg-slate-300 ${account.active===false?'bg-green-600':'bg-red-600'}`}>{account.active===false?'Enable':'Disable'}</button></td></tr>})}{!users.length && <tr><td colSpan="5" className="p-8 text-center text-slate-500">No users found.</td></tr>}</tbody></table></div></section>}
  </main>;
}
function Field({ label, wide = false, children }) { return <label className={wide ? 'md:col-span-2' : ''}><span className="label">{label}</span>{children}</label>; }
